---
title: "PFAS and DM meta analysis"
author: "Xin Yu"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")
```

# Numeric variables
## Marginal distribution
```{r, warning=FALSE, message=FALSE}
# library
library(ggplot2)
library(ggExtra)
library(dplyr)

set.seed(1234)
cluster1 <- data.frame( x=rnorm(5000, 10, 1.9), y=rnorm(5000, 10, 1.2) ,cluster="A")
cluster2 <- data.frame( x=rnorm(5000, 14.5, 1.9), y=rnorm(5000, 14.5, 1.9) ,cluster="B")
cluster3 <- data.frame( x=rnorm(10000, 9.5, 1.9), y=rnorm(10000, 15.5, 1.9) ,cluster="C")
data <- rbind(cluster1,cluster2,cluster3)


p<-ggplot(data, aes(x, y))+
  geom_point()
ggMarginal(p, margins="both", type="histogram")

```

```{r, warning=FALSE, message=FALSE}
p<-ggplot(data, aes(x, y, color = cluster))+
  geom_point()+
  theme(legend.position = "bottom")

ggMarginal(p,groupColour=T,groupFill=T)
```


```{r, warning=FALSE, message=FALSE}

p<-ggplot(data, aes(x, y, color = cluster))+
  geom_point()+
  theme(legend.position = "bottom")

p1<-ggMarginal(p,type = "boxplot",groupColour=T,groupFill=T)
p2<-ggMarginal(p,type = "density",groupColour=T,groupFill=T)

p1$grobs[p1$layout$name == "topMargPlot"] <- p2$grobs[p1$layout$name == "topMargPlot"]
p1

```


## density plot
```{r, warning=FALSE, message=FALSE}
library(ggplot2)
library(hexbin)

# Basic scatterplot with group
ggplot(data, aes(x=x, y=y) ) +
  geom_point(alpha=0.2)

# Basic scatterplot with group
ggplot(data, aes(x=x, y=y,col=cluster) ) +
  geom_point(alpha=0.2)

# 2d histogram
ggplot(data, aes(x=x, y=y) ) +
  geom_bin2d(bins = 70) +
  scale_fill_continuous(type = "viridis")

# 2d Hexbin
ggplot(data, aes(x=x, y=y) ) +
  geom_hex(bins = 70) +
  scale_fill_continuous(type = "viridis") 

# Using raster
ggplot(data, aes(x=x, y=y) ) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))

# Area + contour
ggplot(data, aes(x=x, y=y) ) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", colour="white")
```

## Ridgeline plot
```{r, warning=FALSE, message=FALSE}
library(ggridges)
library(ggplot2)

str(lincoln_weather)

ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`, group=`Month`))+
  geom_boxplot()

ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`, fill = ..x..)) +
  geom_density_ridges_gradient()+
  scale_fill_gradientn(
    colors = c("#0571b0", "#92c5de", "#f7f7f7", "#f4a582", "#ca0020"),
    name = "Temp (°F)",
    limits = c(0,100) # Consistent scale
  )

```

# Categorical variables
## Donut chart
```{r, warning=FALSE, message=FALSE}
library(ggplot2)
 
# Create test data.
data <- data.frame(
  category=c("A", "B", "C"),
  count=c(10, 60, 30)
)
 
# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
data$label <- paste0(data$category, "\n value: ", data$count)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
  geom_rect() +
  geom_text(x=1.5, aes(y=labelPosition, label=label, color=category), size=6) + # x here controls label position (inner / outer)+
  coord_polar(theta="y") +
  xlim(c(-1, 4)) +
  theme_void() +
  theme(legend.position = "none")
```

## Venn plot
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggVennDiagram)

# Create the dataframe with comma-separated outcome windows
study_data <- data.frame(
  study_id = 1:100,
  outcome_window = sapply(1:100, function(x) {
    windows <- sample(c("gestation", "childhood", "adulthood"), 
                     size = sample(1:3, 1), # Each study has 1-3 outcome windows
                     replace = FALSE)
    paste(windows, collapse = ",")
  }),
  stringsAsFactors = FALSE
)

# Create the window_count list using tidyverse
window_count <- study_data %>%
  # Split comma-separated values into rows
  separate_rows(outcome_window, sep = ",") %>%
  # Group by outcome window
  group_by(outcome_window) %>%
  # Get sorted list of study_ids for each window
  summarise(study_ids = list(sort(study_id))) %>%
  # Convert to named list
  deframe() %>%
  as.list()

ggVennDiagram(window_count,label="count",category.names = c("gestation","childhood","adulthood"),label_alpha = 0,edge_size = 0.1,label_size=5)+
  scale_fill_gradient(low = "#F4FAFE", high = "#888888") +
  ggtitle("Count of Studies by Exposure Window")+
  theme(legend.position = "none")
```


## Upset plot
```{r, warning=FALSE, message=FALSE}
library(ggupset)
library(ggplot2)

set.seed(1234)
# Create the dataframe with comma-separated outcome windows
study_data <- data.frame(
  study_id = 1:100,
  window = sapply(1:100, function(x) {
    windows <- sample(c("preconception", "gestation", "childhood", "adolescence", "adulthood"), 
                     size = sample(1:3, 1), # Each study has 1-3 outcome windows
                     replace = FALSE)
    paste(windows, collapse = ",")
  }),
  stringsAsFactors = FALSE
)

study_data$window2 <- lapply(strsplit(study_data$window, split = ","), function(x) trimws(x))

ggplot(study_data,aes(x=window2)) +
  geom_bar(width=0.5) +
  #geom_text(stat='count', aes(label=after_stat(count)), vjust=-1) +
  scale_y_continuous(limits = c(0, 15), breaks = seq(0,15,5)) + 
  scale_x_upset(sets=c("preconception","gestation","childhood","adolescence","adulthood"))+
  xlab("Exposure Window")+
  ylab("")+
  ggtitle("Number of Studies by Exposure Window")+
  theme_minimal()+
  theme(axis.text.y=element_text(size=12))
```

# Geofacet
```{r, warning=FALSE, message=FALSE}
library(geofacet)
library(ggplot2)

head(state_unemp)


ggplot(state_unemp, aes(year, rate)) +
  geom_line() +
  facet_wrap(~ state,axes="all") +
  labs(title = "Seasonally Adjusted US Unemployment Rate 2000-2016",
    caption = "Data Source: bls.gov",
    x = "Year",
    y = "Unemployment Rate (%)") +
  theme(strip.text.x = element_text(size = 6))

head(us_state_grid2)

ggplot(state_unemp, aes(year, rate)) +
  geom_line() +
  facet_geo(~ state, grid = "us_state_grid2", label = "name") +
  #ylim(c(0,15))+
  labs(title = "Seasonally Adjusted US Unemployment Rate 2000-2016",
    caption = "Data Source: bls.gov",
    x = "Year",
    y = "Unemployment Rate (%)") +
  theme(strip.text.x = element_text(size = 6))
```




